apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app-op
  labels:
    app: chat-app-op

spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-app-op

  template:
    metadata:
      labels:
        app: chat-app-op

    spec:
      containers:
      - name: chat-app-op

        image: callicoder/spring-boot-websocket-chat-demo:0.0.1-SNAPSHOT ## need to replace with original image
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: chat-app-op
  labels:
    app: chat-app-op

spec:
  type: NodePort
  selector:
    app: chat-app-op

  ports:
  - name: http
    port: 8090
    targetPort: 8090
